name: Deploy Flask App to Azure Web App - mojaplikacja84

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip -r release.zip app.py requirements.txt static/ templates/

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_01F37DC921D843BD8304F2F7DEB18BCC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_09C9036B167D470EA901BBD0EC21D960 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BE24A99C7D4A4667BEF448BFB62D8431 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mojaplikacja84'
          slot-name: 'Production'
          package: release.zip